// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { CellulaLife, CellulaLifeData, CellulaLifeTableId } from "./tables/CellulaLife.sol";
import { UserCoins, UserCoinsTableId } from "./tables/UserCoins.sol";
