// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { CellulaLifeData } from "./../tables/CellulaLife.sol";

interface ISaveLifeInfoSystem {
  function saveLifeInfo(uint256 tokenId, uint8 viewRange, uint8 attack, string memory moveRule) external payable;

  function lifeInfo(uint256 tokenId) external returns (CellulaLifeData memory dataInfo);

  function getAttack(uint256 tokenId) external returns (uint8 attack);

  function getMoveRule(uint256 tokenId) external returns (string memory moveRule);

  function getViewRange(uint256 tokenId) external returns (uint8 viewRange);
}
